version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: soft
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=soft
      - DB_NAME=postgres
      - DB_PORT=5432
    depends_on:
      - db
    volumes:
      - .:/usr/src/

volumes:
  pgdata:
